version: "3.7"

services:
    app:
        build:
            context: .
        container_name: fregata_bundle_app
        restart: on-failure
        tty: true
        stdin_open: true
        network_mode: host
        volumes:
            - ./:/var/www/html